// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GreenPlay
{
public static class GPGSlds
{
        public const string achievement_score_reached_1200 = "CgkIw6a8t_gCEAIQEw"; // <GPGSID>
        public const string achievement_score_reached_75 = "CgkIw6a8t_gCEAIQAw"; // <GPGSID>
        public const string achievement_score_reached_1300 = "CgkIw6a8t_gCEAIQFA"; // <GPGSID>
        public const string achievement_score_reached_50 = "CgkIw6a8t_gCEAIQAg"; // <GPGSID>
        public const string achievement_score_reached_900 = "CgkIw6a8t_gCEAIQDg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIw6a8t_gCEAIQGg"; // <GPGSID>
        public const string achievement_score_reached_1100 = "CgkIw6a8t_gCEAIQEg"; // <GPGSID>
        public const string achievement_you_planted_two_trees = "CgkIw6a8t_gCEAIQGA"; // <GPGSID>
        public const string achievement_score_reached_1000 = "CgkIw6a8t_gCEAIQDw"; // <GPGSID>
        public const string achievement_played_for_first_time = "CgkIw6a8t_gCEAIQAQ"; // <GPGSID>
        public const string achievement_score_reached_800 = "CgkIw6a8t_gCEAIQDQ"; // <GPGSID>
        public const string achievement_score_reached_700 = "CgkIw6a8t_gCEAIQDA"; // <GPGSID>
        public const string achievement_score_reached_600 = "CgkIw6a8t_gCEAIQCw"; // <GPGSID>
        public const string achievement_score_reached_500 = "CgkIw6a8t_gCEAIQCg"; // <GPGSID>
        public const string achievement_score_reached_400 = "CgkIw6a8t_gCEAIQCQ"; // <GPGSID>
        public const string achievement_score_reached_300 = "CgkIw6a8t_gCEAIQCA"; // <GPGSID>
        public const string achievement_score_reached_200 = "CgkIw6a8t_gCEAIQBQ"; // <GPGSID>
        public const string achievement_score_reached_100 = "CgkIw6a8t_gCEAIQBA"; // <GPGSID>
        public const string achievement_score_reached_1500 = "CgkIw6a8t_gCEAIQFg"; // <GPGSID>
        public const string event_planted_a_tree = "CgkIw6a8t_gCEAIQEQ"; // <GPGSID>
        public const string achievement_you_planted_one_tree = "CgkIw6a8t_gCEAIQBw"; // <GPGSID>
        public const string achievement_score_reached_2000 = "CgkIw6a8t_gCEAIQFw"; // <GPGSID>
        public const string achievement_score_reached_1400 = "CgkIw6a8t_gCEAIQFQ"; // <GPGSID>

}
}
